### PR TITLE
Feat ct dockets updates

### PR DESCRIPTION
**Pull request by NewtonMutugi**
- Unretired scripts on Remove_CT_ODS_Duplicates
- Updated CT_Dockets scipts by removing the ODS_Logs insert from all relevant scripts

### CODE REVIEW

**Comment by nobert-mumo** [comment]
@NewtonMutugi, I see the change is on a lot of files. Maybe you can give a bit more context on the PR description to enable the reviewers have better context when reviewing.

**Comment by NewtonMutugi** [comment]
@nobert-mumo here is a more detailed explanation of what the PR is changing:

1. Moving ODS/CT_DOCKET/Remove_CT_ODS_Duplicates/Retired scripts from Retired directory to the Remove_CT_ODS_Duplicates director above it. 
2. Removed the ODS_Logs insert statements from the CT_Dockets since they are redundant

I hope this is clearer, though @DennisGibz can provide any further clarification

**Comment by DennisGibz** [comment]
@nobert-mumo we had enhanced the ODS scripts specifically the C&T ones to be prone of fetching duplicates and then retiring the scripts that remove duplicates just to improve on the ETL runtime.

However, I noted the following, we have some duplicates as a result on running the data cleaning and standardizing scripts.

So the script is just rolling back the previously made changes that we will always have the script to remove duplicates from ODS.

**Review by DennisGibz — COMMENTED** [review]
@NewtonMutugi  the remove duplicate on CT_PatientLab has a syntax error.

**Review by nobert-mumo — APPROVED** [review]
@NewtonMutugi , @DennisGibz thanks for the context. LGTM.

**Pull request merged**
