### PR TITLE
Adding changes to ARTOutcomes model

### PR DESCRIPTION
**Pull request by Marymary-dev**

### CODE REVIEW

**Comment by DennisGibz** [comment]
@Marymary-dev Is it LIHMIS or LHMIS? Depending on your abbreviation, harmonize on the script accordingly.

      	   union all
		select 'LIHMIS' as ARTOutcome
and 

WHEN [ARTOutcome] = 'LHMIS'  THEN 'LOST IN HMIS'

**Comment by Marymary-dev** [comment]
> @Marymary-dev Is it LIHMIS or LHMIS? Depending on your abbreviation, harmonize on the script accordingly.
> 
> ```
>   	   union all
> 	select 'LIHMIS' as ARTOutcome
> ```
> 
> and
> 
> WHEN [ARTOutcome] = 'LHMIS' THEN 'LOST IN HMIS'

@DennisGibz  the I has been added in the DimARTOutcome

**Review by DennisGibz — APPROVED** [review]

**Comment by DennisGibz** [comment]
@Marymary-dev , Just and been curious.  You had added the same on the Intermediate outcomes table then later closed the PR. How will above amendment on the Dim marry what we will have on the Intermediate outcomes?

**Comment by Marymary-dev** [comment]
> @Marymary-dev , Just and been curious. You had added the same on the Intermediate outcomes table then later closed the PR. How will above amendment on the Dim marry what we will have on the Intermediate outcomes?

@DennisGibz  this PR has 2 files that were changed

**Review by nobert-mumo — APPROVED** [review]

**Comment by DennisGibz** [comment]
@Marymary-dev  by " DATEADD(day, 1 - DAY(GETDATE()), GETDATE()) " what happens if an upload is done at 30th or 31st of the reporting month?  According to the script the site will be classified as LOST IN HMIS?

**Comment by Marymary-dev** [comment]
All uploads should be done between 1st and 15th , this is the guidance for reporting

**Pull request merged**
