### PR TITLE
Feauture  add index patient pk

### PR DESCRIPTION
**Pull request by Marymary-dev**

### CODE REVIEW

**Review by DennisGibz — CHANGES_REQUESTED** [review]
@Marymary-dev isn't IndexPatientPK not a PII? If it is, we can use IndexPatientPkHash which is already available in ODS.

**Comment by Marymary-dev** [comment]
> @Marymary-dev isn't IndexPatientPK not a PII? If it is, we can just expose IndexPatientPkHash in NDWH and reporting respectively.

@DennisGibz thanks, this was done

**Review by DennisGibz — CHANGES_REQUESTED** [review]
@Marymary-dev  kindly remove the IndexPatientPk column on the final select into.

**Comment by Marymary-dev** [comment]
> @Marymary-dev kindly remove the IndexPatientPk column on the final select into.

@DennisGibz  Done

**Review by DennisGibz — APPROVED** [review]
All now working as expected.

**Pull request merged**
