### PR TITLE
Adding linelist modules uptake

### PR DESCRIPTION
**Pull request by Marymary-dev**

### CODE REVIEW

**Comment by nobert-mumo** [comment]
@Marymary-dev was checking if there were any reservations for not extending  `all_EMRSites` ? I feel the variables can natually fit there & utilise the same table.

**Comment by Marymary-dev** [comment]
I see what you mean, this is so that the dashboards also read from here ?

**Comment by nobert-mumo** [comment]
> I see what you mean, this is so that the dashboards also read from here ?

yeah, I think that would be another use case. I just thought instead of creating another facility level linelist, we can utilize the  all emrsites table, since the modules uptake actually feels like a 'characteristic' of a facility which is what all emrsites contains.

**Comment by Marymary-dev** [comment]
> @Marymary-dev was checking if there were any reservations for not extending `all_EMRSites` ? I feel the variables can natually fit there & utilise the same table.
@nobert-mumo  kindly review, changes have been made

**Review by nobert-mumo — APPROVED** [review]
LGTM @Marymary-dev

**Pull request merged**
