### PR TITLE
Renaming mfl codes

### PR DESCRIPTION
**Pull request by Marymary-dev**

### CODE REVIEW

**Review by nobert-mumo — COMMENTED** [review]
@Marymary-dev, not sure I see the changes ?

**Comment by Marymary-dev** [comment]
@Nobert it is here :
https://github.com/palladiumkenya/dwh-etl/pull/204/commits/82a23e4e326eb944438e5f10141c42c3d1b6f99f

**Comment by Marymary-dev** [comment]
> @Marymary-dev, not sure I see the changes ?

They are here: 
https://github.com/palladiumkenya/dwh-etl/pull/203/commits/82a23e4e326eb944438e5f10141c42c3d1b6f99f

**Comment by Marymary-dev** [comment]
> > @Marymary-dev, not sure I see the changes ?
> 
> They are here: [82a23e4](https://github.com/palladiumkenya/dwh-etl/commit/82a23e4e326eb944438e5f10141c42c3d1b6f99f)

@nobert-mumo  are we good now on this?

**Comment by nobert-mumo** [comment]
> > > @Marymary-dev, not sure I see the changes ?
> > 
> > 
> > They are here: [82a23e4](https://github.com/palladiumkenya/dwh-etl/commit/82a23e4e326eb944438e5f10141c42c3d1b6f99f)
> 
> @nobert-mumo are we good now on this?

@Marymary-dev  Looks good, I think the other changes are captured in the other PR. the only thing I wanted to confirm was it intentional `REPORTING.[dbo].[LineListTransPNS]`

**Pull request merged**
