### PR TITLE
Added covid aggregate table

### PR DESCRIPTION
**Pull request by cbrianbet**
Also added Missing agegroup column in FactCovid

### CODE REVIEW

**Review by nobert-mumo — COMMENTED** [review]
@cbrianbet for the covid I guess we would also need to include a denominator for TXCurr ? o that we have both an adult_count and TXCurr count. WDYT ?

**Comment by cbrianbet** [comment]
> @cbrianbet for the covid I guess we would also need to include a denominator for TXCurr ? o that we have both an adult_count and TXCurr count. WDYT ?

@nobert-mumo what if we add a where clause where txcurr =1 so that we onlt have aggregates for those in care 
I dont think we use any data for those not in care in the covid dataset

**Comment by Marymary-dev** [comment]
No we don't use for the not active patients

**Comment by nobert-mumo** [comment]
> > @cbrianbet for the covid I guess we would also need to include a denominator for TXCurr ? o that we have both an adult_count and TXCurr count. WDYT ?
> 
> @nobert-mumo what if we add a where clause where txcurr =1 so that we onlt have aggregates for those in care I dont think we use any data for those not in care in the covid dataset

Ah okay, I thought there was a use case for showing that. In that case we can indeed just filter for active ones.

**Comment by cbrianbet** [comment]
Now resolved 
Added where clause

**Review by nthusi-codes — APPROVED** [review]

**Pull request merged**
