### PR TITLE
Optimize_StartRegimens_aggregate

### PR DESCRIPTION
**Pull request by Marymary-dev**

### CODE REVIEW

**Comment by nthusi-codes** [comment]
@Marymary-dev. The merge target should be the dev branch

**Comment by Marymary-dev** [comment]
Sure

**Comment by nobert-mumo** [comment]
Hi @Marymary-dev, had a look at the file:
- I think we should be building the Aggregates from the fact table and not the linelist ?
- For the TRUNCATE apporach I think `select ...into` doesn't work,instead we need `insert into ..`
- For the naming of the table we could stick with the convention of CamelCase e.g `REPORTING.dbo.AggregateOptimizeStartRegimen`
- Maybe would be worth checking if we can already combine `AggregateOptimizeStartRegimen` & `.AggregateOptimizeCurrentRegimen` since they look very similar.

**Review by cbrianbet — CHANGES_REQUESTED** [review]
I see this is merging into master rather than dev

**Review by nobert-mumo — CHANGES_REQUESTED** [review]
Hi @Marymary-dev , please see the comments. Thx.

**Pull request merged**
