### PR TITLE
Added ODS DQC scripts

### PR DESCRIPTION
**Pull request by NewtonMutugi**

### CODE REVIEW

**Review by DennisGibz — COMMENTED** [review]
Nice work. However, We need to change the select statements returning all the columns with an aggregate select statement which returns a count of the null PatientPKHash or PatientIDhash grouped by the same.

**Comment by nobert-mumo** [comment]
@NewtonMutugi @DennisGibz just trying to understand 
- why do we join on PatientIDHash and PatientPKHash and not the usual PatientPKHash and SiteCode
- why are we interested on null PatientPKs and PatientIDs that are not voided? Maybe I missed it
- 
Otherwise, nice stuff with the checks. We can probably add them to Metabase or OpenMetadata to track them.

**Review by Marymary-dev — COMMENTED** [review]
@NewtonMutugi  there is a problem here if you leave the join on Sitecode as well, remove the join on PatietIDhash

**Review by DennisGibz — APPROVED** [review]
Good work. Next, we will now have the scripts on Metabase for monitoring. We will liase with @nobert-mumo for this.

**Comment by DennisGibz** [comment]
@Marymary-dev  what we are trying to do is flag the patients whose PatientID and and PatientPK have not been hashed during the ETL process(Hashing is done based on CT_Patient). They are potential orphan records and if its the case,they should be voided.
 This PR is intended to show the unhashed  records on metabase for action.

Hope it's now clear.

**Pull request merged**
