### PR TITLE
Added scripts to update records for voided patients

### PR DESCRIPTION
**Pull request by cbrianbet**
- Added scripts to update records for voided patients
- Added scripts to void patients (CT, HTS, MNCH) on ODS for patients who don't exist from the source
- Added CT_CancerScreening and CT_ARTFastTrack

### CODE REVIEW

**Comment by nobert-mumo** [comment]
@DennisGibz I was wm=ondering for the voiding of patients e.g. `CT_VoidedPatientCheck.sql`, why do we have to inner join to the same table again on the update part ?

**Comment by nobert-mumo** [comment]
@cbrianbet was the PR meant to void only the CT extracts. Will there be another one for the other dockets ?

**Comment by DennisGibz** [comment]
> @cbrianbet
> 
> * I was wondering for the voiding of patients e.g. `CT_VoidedPatientCheck.sql`, why do we have to inner join to the same table again on the update part ?
> * For the voiding of the patients what about prep docket ?

@nobert-mumo you mean

"UPDATE a
	SET a.voided =1
FROM [ODS].[dbo].[CT_AdverseEvents] a
  JOIN [ODS].[dbo].[CT_Patient] b
  ON	a.SiteCode = b.SiteCode AND 
		a.PatientPK = b.PatientPK
WHERE b.voided =1 "

Its nessesary because at this point, we want to void the associated records for the voided patients. So the flow is,we void patient then go the records associated with the patient.

On PrEP, a PR can be done later together with voiding of other dockets.

**Comment by nobert-mumo** [comment]
> > @cbrianbet
> > 
> > * I was wondering for the voiding of patients e.g. `CT_VoidedPatientCheck.sql`, why do we have to inner join to the same table again on the update part ?
> > * For the voiding of the patients what about prep docket ?
> 
> @nobert-mumo you mean
> 
> "UPDATE a SET a.voided =1 FROM [ODS].[dbo].[CT_AdverseEvents] a JOIN [ODS].[dbo].[CT_Patient] b ON a.SiteCode = b.SiteCode AND a.PatientPK = b.PatientPK WHERE b.voided =1 "
> 
> Its nessesary because at this point, we want to void the associated records for the voided patients. So the flow is,we void patient then go the records associated with the patient.
> 
> On PrEP, a PR can be done later together with voiding of other dockets.

@DennisGibz  not really, I meant on the patient_voiding folder,
I thought we could shorten the update section to be more clear by : 


> > @cbrianbet
> > 
> > * I was wondering for the voiding of patients e.g. `CT_VoidedPatientCheck.sql`, why do we have to inner join to the same table again on the update part ?
> > * For the voiding of the patients what about prep docket ?
> 
> @nobert-mumo you mean
> 
> "UPDATE a SET a.voided =1 FROM [ODS].[dbo].[CT_AdverseEvents] a JOIN [ODS].[dbo].[CT_Patient] b ON a.SiteCode = b.SiteCode AND a.PatientPK = b.PatientPK WHERE b.voided =1 "
> 
> Its nessesary because at this point, we want to void the associated records for the voided patients. So the flow is,we void patient then go the records associated with the patient.
> 
> On PrEP, a PR can be done later together with voiding of other dockets.

@DennisGibz not really, meant on the patient_voiding folder. Maybe to make it more clear & shorten we can do:

`UPDATE [ODS].[dbo].[CT_Patient]
    SET VOIDED =1
FROM [ODS].[dbo].[CT_Patient] a
where concat(a.PatientPK, a.SiteCode) NOT IN (SELECT PatientConcatColumn FROM Src_PatientConcat);`

**Comment by DennisGibz** [comment]
> * Added scripts to update records for voided patients
> * Added scripts to void patients (CT, HTS, MNCH) on ODS for patients who don't exist from the source
> * Added CT_CancerScreening and CT_ARTFastTrack

@nobert-mumo I had tried this, and I found it not to be very accurate hence resulting to doing the concat separately then joining the two result sets.

**Comment by nobert-mumo** [comment]
> > * Added scripts to update records for voided patients
> > * Added scripts to void patients (CT, HTS, MNCH) on ODS for patients who don't exist from the source
> > * Added CT_CancerScreening and CT_ARTFastTrack
> 
> @nobert-mumo I had tried this, and I found it not to be very accurate hence resulting to doing the concat separately then joining the two result sets.

@DennisGibz  okay, that's strange but if it works that's okay. It's a bit hard to understand the join at a glance.

**Comment by nobert-mumo** [comment]
@DennisGibz  generally  LGTM.
I just had two suggestions:
- Maybe we can look to move most of subfolders form utils to ODS that seem to be part of core ETL for ODS?
- We could format the queries to make them more readabale.

**Review by nobert-mumo — APPROVED** [review]

**Pull request merged**
