### PR TITLE
Fix update mhealth table names

### PR DESCRIPTION
**Pull request by NewtonMutugi**
Updated mhealth table names on ODS. 
Table name format: Mhealth_ApplicationName_TableName

- from Ushauri_HEI to Mhealth_Ushauri_HEI
- from Ushauri_HWExposure to Mhealth_Ushauri_HWExposure
- from Ushauri_Patient to Mhealth_Ushauri_Patient
- from Ushauri_PatientAppointments to Mhealth_Ushauri_PatientAppointments
- from Ushauri_PatientLabs to Mhealth_mLab_PatientLab
- from Ushauri_PatientReferral to Mhealth_FacilityReferral_Patient

### CODE REVIEW

**Review by DennisGibz — COMMENTED** [review]
Did you manage to explore other places where the old table names had been referenced?
especially on the NDWH layer?

**Comment by NewtonMutugi** [comment]
Yes I only found two tables that had references to the the mhealth tables i.e. load dim patients and load fact ushauri appointments

**Comment by DennisGibz** [comment]
@NewtonMutugi Ushauri_Patient  and appointments have been referenced on the NDHW layer .Kindly check.

**Comment by DennisGibz** [comment]
> @NewtonMutugi Ushauri_Patient and appointments have been referenced on the NDHW layer .Kindly check.

Ignore the below comment if above has been addressed.

**Review by DennisGibz — APPROVED** [review]

**Comment by NewtonMutugi** [comment]
Okay though I'm seeing a merge conflict has appeared so let me fix it before merging the changes. Thanks

**Comment by DennisGibz** [comment]
Sure

**Comment by NewtonMutugi** [comment]
Merge conflict fixed proceeding to merge pull request now

**Pull request merged**
