### PR TITLE
Adding new intermediate tables for use in creating downstream models

### PR DESCRIPTION
**Pull request by nobert-mumo**

### CODE REVIEW

**Review by Marymary-dev — COMMENTED** [review]
Remember to remove the use NDWH

**Review by cbrianbet — APPROVED** [review]

**Review by Marymary-dev — COMMENTED** [review]
In CT_PatientLabs kindly check if we have Qualitative HIVViral load, LDL as viral load test names so that we don't leave out any viral load tests that are there

**Comment by nobert-mumo** [comment]
> In CT_PatientLabs kindly check if we have Qualitative HIVViral load, LDL as viral load test names so that we don't leave out any viral load tests that are there

@Marymary-dev  thanks for this, Iactually think this is taken care of in the cleaning scripts. See this look up table: https://github.com/palladiumkenya/Data-Models/blob/master/staging_cleaning_scripts/look_up_tables/lkp_test_name.sql.

I also did a test to make sure the no of rows returned in the current view = no of rows in the new intermediate table. They matched 100%

**Comment by Marymary-dev** [comment]
Thank you @***@***.***
***@***.***>

**Pull request merged**
